openapi: '3.0.1'
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
paths: { $ref: 'Path.yaml' }
components: { $ref: '../Generic/Components.yaml' }
servers:
- url: 'https://localhost:8080'
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
